- backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/dto/MyProfileResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/dto/OtherProfileResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- close #22 
- close #24 
- close #31 
프로필 페이지에 들어온 해당 사용자를 쿠키를 통해 해당 사용자인지, 타인인지 조회하는 기능을 추가했습니다.
내 프로필 페이지인지와 타인의 프로필 페이지인지를 나누고 해당 사용자의 닉네임, 이메일, 작성한 게시글, 팔로워 수, 팔로잉 수를 불러와서 반환해주는 api를 구현했습니다. 타인의 페이지인 경우 로그인한 사람이 팔로우 했는지에 대한 여부도 같이 반환해주게 됩니다.
> feat: 프로필 들어온 사용자 조회 및 프로필 정보 조회

- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- #34
- PostService의 searchByTags() 메서드 내부 로직 수정
- ImageRepository에 getImagesOfRecentPostsByTags() 메서드 추가
- POST, POST_HASHTAG, HASHTAG, IMAGE 테이블을 join하여 List<image> 반환
- 태그 이름 관련 조건절을 생성하는 createTagNameConditionalStatement() 메서드 추가
- 인자로 주어진 태그 이름들을 " OR "로 연결하여 조건절 생성
- PostRepository의 searchByHashtags(), createWhereStatement() 메서드 삭제
- PostsSearchResponse 응답 객체에 Builder 패턴 적용
PostService의 searchByTags() 메서드의 기존 로직은, hashtagRepository로 태그 이름에 해당하는 태그의 아이디를 가져오고, postRepository를 통해 해당 태그를 가지고 있는 post를 가져온 다음, ImageRepository를 통해 post의 아이디로 image를 가져왔습니다. 이 방식은 쿼리를 총 3번이나 보내기 때문에 조회 속도 저하 등의 문제가 있고, 그래서 쿼리를 3번 보내는 대신 `imageRepository.getImagesOfRecentPostsByTags()`를 호출하도록 수정하였습니다.
> feat: 키워드를 통한 게시물 검색 시 사용하는 쿼리문 수정 및 리팩토링

- backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyNickNameForm.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/dto/NewNickNameForm.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #26 
닉네임 변경 로직을 구현했습니다. User 컨트롤러, 서비스, 리포지토리에 닉네임 변경 함수를 추가했고, dto 클래스를 추가했습니다.
닉네임 변경 서비스 로직은 먼저 로그인 세션이 만료되었는지 체크하고, 바꾸려는 기존 닉네임이 데이터베이스에 있는지 확인하고, 바꾸려는 닉네임이 데이터베이스에 있는 닉네임들과 중복되는지 체크하고, 새로운 닉네임을 반영하는 로직으로 구현했습니다. 기존 닉네임이 데이터베이스에 없을 경우 예외처리 했을 때 핸들링하는 로직이 컨트롤러에 구현이 되어 있지 않아서 그 부분까지 구현했습니다. 
테스트는 postman으로 예외처리 확인까지 모두 진행 완료하였습니다.
> feat: 닉네임 변경

- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/HashtagNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- #122 
- 외부 DB에 저장되어있는 샘플 데이터로 테스트 실행
- 테스트 코드를 작성하여 테스트 실행 중 쿼리문을 잘못 작성한 것을 발견하였으며, 쿼리문에서 문자열을 사용할 때 ''로 감싸도록 수정
- `HashtagNotExistException`의 에러 메시지를 외부에서 인자로 주는 것이 아니라 `exception` 클래스에서 관리하도록 변경
- `UserServiceTest`의 테스트 실패하는 메서드를 성공하도록 변수의 값 수정
> test: 해시태그를 통한 게시물 검색 기능 테스트 코드 작성

- backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyPasswordForm.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/exception/IdNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NotLoginStatementException.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #29 
비밀번호 변경 로직을 구현하였습니다.
먼저 로그인을 한 사용자인지 체크하고, 기존 비밀번호와 입력한 비밀번호가 맞는지 확인하는 과정을 거친 후에 새로운 비밀번호를 반영하게 됩니다. 이 기능을 구현하는 과정에서 세션에 user를 저장해서 세션을 통해 user정보를 꺼내오는 로직을 다시 생각해 보게 되었고, 심각한 오류라고 생각하여 세션에 user id만 저장하고 저장한 user id를 통해 db에서 그때그때 user 정보를 불러오도록 수정하였습니다. 
포스트맨을 통해 비밀번호 변경 성공, 로그인 세션 만료, 비밀번호 변경 실패 모두 테스트 완료했습니다.
> feat: 비밀번호 변경

- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/HashtagSearchResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- #141
- 해시태그 검색의 응답에 사용할 `HashtagSearchResponse` 응답 객체 생성
- `HashtagRepository`에 접두어로 해시태그를 검색하는 searchHashtagByPrefix() 메서드 구현
- `HashtagService` 클래스 생성 및 해시태그 검색 기능 구현
- searchHashTag(): 인자로 주어진 키워드로 시작하는 해시태그를 검색하여 HashtagSearchResponse를 반환
- `HashtagController` 클래스 생성 및 해시태그 검색 API 구현]
- searchHashTag(): 쿼리 파라미터로 주어진 키워드로 시작하는 해시태그를 검색하여 그 결과에 대한 응답을 반환
- SpringController는 매개 변수의 "+" 문자를 공백으로 대체하기 때문에, `PostService`의 `searchByTags()`에서 태그 이름을 구분하는 구분자를 "+"에서 공백으로 변경
- `PostService` 로직 변경에 따라 `PostServiceTest`의 테스트 코드도 변경
> feat: 해시태그 검색 기능 구현

- backend/carbook/src/test/java/softeer/carbook/domain/hashtag/service/HashtagServiceTest.java
- #145
- PostService의 해시태그 검색 기능(searchHashTag)을 테스트하는 테스트 코드 작성
> test: 해시태그 검색 기능 테스트 코드 작성

- backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- close #140 
새로운 데이터베이스에 default값이 false인 is_deleted boolean column을 추가해야 합니다.
upsert 쿼리 수행을 위해 follower_id와 following_id의 복합키 설정이 필요합니다.
is_deleted를 활용하도록 followRepository, imageRepository를 일부 변경하였습니다.
신규 팔로우인 경우 insert, 과거 팔로우했었던 경우 update 수행하는 upsert 로직으로 변경하였습니다.
> refactor: 팔로우/언팔로우 방식 soft delete로 변경

- frontend/carbook/src/components/Home/HashtagList.ts
- frontend/carbook/src/components/Home/PostList.ts
- frontend/carbook/src/components/Home/SearchForm.ts
- frontend/carbook/src/store/index.ts
- frontend/carbook/src/store/tagStore.ts
createStore를 모듈로 분리하였습니다
- close #109 
이전 생성됐던 렌더 함수가 쌓이는 문제를 해결하고, createStore를 모듈화 하였습니다.
store/index.ts 를 보면 createStore 함수가 존재합니다
사용 방법은 관리하고 싶은 데이터가 있을 때 store에 파일을 하나 만든 후
reducer만 정의하여 createStore을 불러와 store을 생성해주면 됩니다.
action은 type과 payload 키값을 가집니다.
type은 액션이름. payload는 필요한  data를 처리할 수 있습니다.
<정리>
1. store에 파일을 만든 후 reducer를 정의, createStore함수를 불러와 store을 생성한다.
2. 컴포넌트의 렌더함수가 해당 store을 구독하고 싶으면 store이름.subscribe(this, this.render.bind(this)) 형태로 작성
+ subscribe는 컴포넌트 이름과 렌더 함수를 전달 해야하는데... 형태가 보기 좋진 않아서
함수 형태에 대해 좋은 방법이 있다면... 알려주세요
3. 그러면 state변경시 store의 dispatch함수가 실행되면서 구독했던 렌더링 함수들이 실행된다.
X
X
> chore: store 구조 모듈화

- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- #134
- `myProfile()`: 나의 프로필 페이지인 경우 프로필 정보(닉네임, 이메일, 작성한 게시글, 팔로워 수, 팔로잉 수)를 조회하는 기능을 테스트하는 코드
- `otherProfile()`: 타인의 프로필 페이지인 경우 프로필 정보(닉네임, 이메일, 작성한 게시글, 팔로워 수, 팔로잉 수)와 팔로우 여부를 조회하는 테스트 코드
- 해시태그를 통한 게시물 검색 기능 테스트 코드(`searchByTags()`) 리팩토링
> test:  나의 프로필 페이지, 타인의 프로필 페이지 테스트 코드 작성

- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/Keyword.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TagSearchResopnse.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TagSearchResult.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TypeSearchResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Model.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Type.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
- close #141
포스트맨으로 테스트하였습니다.
- 차량 종류(`Type`) 클래스 생성
- 차량 모델(`Model`) 클래스 생성
- `HashtagRepository`
- 접두어로 차량 종류를 검색하는 `searchTypeByPrefix()` 메서드 구현
- 접두어로 차량 모델을 검색하는 `searchModelByPrefix()` 메서드 구현
- 모든 태그 검색 시 검색 결과를 저장하는 `TagSearchResult` DTO 객체 생성
- 모든 태그 검색의 응답에 사용할 `TagSearchResponse` DTO 응답 객체 생성
- `HashtagService`
- 모든 태그를 검색하는 `searchAllTags()` 기능 구현
- `HashtagController`
- `searchAllTags()`: 쿼리 파라미터로 주어진 키워드로 시작하는 모든 태그를 검색하여 그 결과에 대한 응답을 반환
- `HashtagController`의 `searchType()`
- `HashtagService`의 `searchType()`
`TypeSearchResponse` 응답 객체는 원래 차량 종류 태그 검색의 응답에 사용할 예정이었지만, API 명세 수정에 따라 사용되지 않게 되었습니다. 하지만 차량 종류 전체 조회 API에서 응답 객체로 사용될 수 있으므로 일단 삭제하지 않았습니다.
> feat: 모든 태그 검색 기능 구현

- frontend/carbook/src/components/Profile/FollowLists.ts
- frontend/carbook/src/components/Profile/HeaderContents.ts
- frontend/carbook/src/components/Profile/HeaderInfo.ts
- frontend/carbook/src/components/Profile/Menu.ts
- frontend/carbook/src/pages/Profile/Profile.scss
- frontend/carbook/src/pages/Profile/Profile.ts
- frontend/carbook/src/pages/Signup/Signup.ts
- frontend/carbook/src/store/userStore.ts
- close #72 
- close #78 
- close #74 
프로필 페이지 기능 대부분 구현했습니다.
본인의 페이지의 팔로워, 팔로잉 리스트에서 삭제하는 기능은 아직 구현하지 못했습니다.
스토어는 아직 사용하지 않았고 설계해야할것 같습니다.
https://user-images.githubusercontent.com/43432783/218399478-12d5ba8e-7eed-4d23-aea6-95ee2b6cb4d5.mp4
https://user-images.githubusercontent.com/43432783/218399552-ffbee6d3-b815-47a1-ba13-657dce9a6645.mp4
> feat: 프로필 페이지 api 연동

- frontend/carbook/src/constants/path.ts
- close #193 
닉네임이 한글일 때 404 페이지로 가는 버그를 수정하였습니다.
프로필 페이지에서는 url에서 닉네임을 가져올 때 decode작업을 해줘야 합니다.
X
X
> fix: 프로필 페이지 닉네임 한글일 때 404페이지로 가는 버그 수정

- backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/controller/LikeController.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/dto/ModifyLikeInfoForm.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/service/LikeService.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- close #45 
- close #46 
글 상세 페이지에서 좋아요와 좋아요 취소 기능을 추가했습니다.
먼저 로그인 여부를 판단하고, 좋아요 여부를 판단한 후에, 좋아요 혹은 좋아요 취소 과정을 진행하게 됩니다.
포스트맨을 통해 테스트 완료했습니다.
> feat: 좋아요/좋아요취소 기능 추가

- backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/main/java/softeer/carbook/domain/tag/controller/TagController.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- close #34
기존에는 해시태그로만 게시물 검색이 가능했고, 사용자가 선택한 해시태그들 중 하나라도 가지고 있는 게시물을 검색 결과로 반환했습니다.
차량 종류와 모델 태그가 추가함에 따라 차량 종류와 모델 태그로도 같이 검색할 수 있도록 수정하였고, 키워드를 통한 게시물 검색 기능은 모든 태그를 가지고 있는 게시물만 검색하도록 내부 로직을 수정하였습니다.
또한 `PostsSearchResponse`에 적용된 `Builder` 패턴을 삭제하였고, soft delete를 구현하기 위해 POST 테이블에 `is_deleted` 칼럼을 추가함에 따라, 게시물을 조회하는 모든 쿼리문에 WHERE절 조건으로 `"is_deleted=false"`를 추가하였습니다.
**게시물을 검색할 때 차량 종류, 차량 모델, 해시태그가 필수 값이 아니므로 각각 null인 경우를 처리하기 위해 `PostService`의 `searchByTags()` 메서드의 로직이 많이 복잡합니다. 리팩토링 관련 좋은 의견 있으시면 남겨주세요!**
> feat: 차량 종류와 차량 모델 태그로도 게시물 검색이 가능하도록 수정

- backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/exception/InvalidPostAccessException.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/exception/PostNotExistException.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/main/java/softeer/carbook/global/dto/Message.java
- backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
- close #198 
글 삭제 기능을 구현하였습니다.
먼저 로그인한 사용자인지 체크하고, 로그인한 사용자이며, 해당 글을 작성했는지 확인하게 됩니다. 해당 글을 작성하지 않은 사용자가 글을 삭제하려고 접근하는 경우 401 응답을 돌려주게 구현했습니다. 삭제는 소프트 딜리트로 구현해서 post 테이블에 is_deleted를 추가해서 true로 변경하는 로직으로 구현했습니다.
포스트맨을 통해 테스트 완료했습니다.
> feat: 글 삭제 기능

- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- close #122
키워드를 통한 게시물 검색 기능 테스트 코드를 작성하였습니다.
- `searchByTagsWithHashtagsAndTypeAndModel()`: 해시태그, 타입, 모델 태그로 게시물을 검색한 경우 테스트
- `searchByTagsWithHashtagsAndModel()`: 해시태그, 모델 태그로 게시물을 검색한 경우 테스트
- `searchByTagsWithHashtagsAndType()`: 해시태그, 타입 태그로 게시물을 검색한 경우 테스트
- `searchByTagsWithHashtags()`: 해시태그로만 게시물을 검색한 경우 테스트
- `searchByTagsWithNoResult()`: 해시태그, 타입, 모델 태그로 게시물을 검색했는데 아무 결과도 얻지 못한 경우 테스트
> test: 키워드를 통한 게시물 검색 기능 테스트 코드 작성

- backend/carbook/src/test/java/softeer/carbook/domain/tag/controller/TagControllerTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
- close #145
- #189 
TagController의 테스트 코드를 작성하였습니다.
- searchAllTags(): 모든 태그 검색 테스트
- searchHashtag(): 해시태그 검색 테스트
- getAllTypes(): 차량 종류 전체 조회 테스트
- getAllModels(): 차량 타입 전체 조회 테스트
> test: TagController 테스트 코드 작성

- backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/tag/service/TagService.java
- backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
'%'가 검색어로 들어올 경우 모든 데이터가 출력되므로, 이를 실제 문자로 인식시키기 위해 쿼리문을 수정하였습니다.
- TagRepository의 쿼리문 수정
- TagService에 로그 출력을 위한 logger 선언 및 사용
- TagServiceTest 테스트 메서드 추가 - searchAllTagsWithNoResult(): 모든 태그 검색 기능 테스트 - 검색 결과가 없는 경우 - searchHashTagWithNoResult(): 해시태그 검색 기능 테스트 - 검색 결과가 없는 경우
> fix: 검색어로 쿼리문에 사용되는 특수문자가 사용되는 경우를 처리하기 위해 쿼리문 수정

- backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- close #233
LIKE 절의 와일드 문자는 '%'와 '_'이므로 이 두 문자가 검색어로 들어올 경우를 처리하기 위해 쿼리문을 수정하였습니다. 와일드 문자를 실제 문자로 인식하기 위해서는 검색어 전체가 아니라 와일드 문자가 들어가는 부분만 '[]'로 감싸야하기 때문에 `convertWildCharToRealChar()`을 사용하여 와일드 문자가 실제 문자로 인식되도록 쿼리문을 수정하였습니다.
- `TagRepository`의 쿼리문 수정
- `convertWildCharToRealChar()`: LIKE 절의 와일드 문자 '%'와 '_'가 쿼리문에서 실제 문자로 인식되도록, 파라미터로 들어온 문자열을 수정하여 반환
> fix: 검색어로 SQL 쿼리문의 특수 문자가 사용되는 경우를 처리하기 위해 쿼리문 2차 수정

- backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- backend/carbook/src/test/java/softeer/carbook/domain/tag/repository/TagRepositoryTest.java
- #233
`TagRepository` 테스트 코드를 작성하던 중, SQL 쿼리의 LIKE 조건절에 쓰이는 와일드 문자가 검색어에 포함될 경우 제대로 조회가 되지 않는 오류를 발견하여, `TagRepository`의 쿼리문의 LIKE 조건절에서 ESCAPE 옵션을 사용하도록 수정하였습니다.
그리고 `TagRepository` 테스트 코드를 작성하였습니다.
> fix: TagRepository의 태그 검색 기능에 쓰이는 모든 쿼리문 수정 및 TagRepository 테스트 코드 작성

- frontend/carbook/src/pages/Profile/Profile.ts
- close #238 
프로필 페이지에서 다른페이지로 이동해도 이전 페이지의 이벤트가 남아있는것을 수정하였습니다.
> Fix : 프로필페이지에서 다른 유저 프로필로 이동할때 state초기화 안되는 버그

- backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- backend/carbook/src/test/java/softeer/carbook/domain/tag/repository/TagRepositoryTest.java
- #145 
- `tagRepository`에 해시태그 id로 해시태그를 조회하는 `findHashtagById()` 메서드 추가
- `findHashtagsByPostId()`: 게시물 id로 해시태그 조회 테스트 코드 작성
- `findModelByName()`: 모델 이름으로 모델 테그 조회 테스트 코드 작성
- 테스트 코드 리팩토링
> test: TagRepositoryTest 테스트 코드 작성 및 리팩토링

- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- close #279 
태그로 게시물 검색 시, 무한 스크롤에서 중복 및 누락 데이터 처리를 위해 기존의 index에서 postId를 활용하도록 PostService의 로직을 수정하였습니다.
- `findImagesOfPostsFromPostId()` 로직 변경
- offset 대신 이전 응답으로 보낸 게시글 중 마지막 게시글의 id를 요청 파라미터로 받기 때문에, 현재 조회한 게시글에서 postId보다 작은 아이디를 가진 Post를 찾은 후, 그 post부터 POST_COUNT 만큼의 개수의 이미지를 응답으로 반환하도록 변경하였습니다.
> feat: 무한 스크롤을 위한 PostService 로직 수정

- backend/carbook/src/main/java/softeer/carbook/domain/like/controller/LikeController.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/like/service/LikeService.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/main/java/softeer/carbook/global/interceptor/LoginInterceptor.java
- backend/carbook/src/test/java/softeer/carbook/domain/like/repository/LikeRepositoryTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/like/service/LikeServiceTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- backend/carbook/src/test/resources/create_table.sql
좋아요 테이블에서 count 함수를 통해 가져오던 좋아요 개수를 
게시글 테이블에 칼럼으로 추가해서 반정규화 진행하였습니다. 성능이 개선되었습니다.
테스트 코드 수정 하였고 포스트맨을 통해 테스트 완료 하였습니다.
> feat: 좋아요 개수 반정규화 진행 구현

- backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- backend/carbook/src/test/resources/create_data.sql
- close #326 
기존에는 로그인한 사용자의 경우 메인페이지에서 팔로우한 사람의 게시글만 보이도록 하였는데, 팔로우한 사람이 없는 신규 사용자의 경우 아무 게시글도 보이지 않습니다. 이를 개선하기 위해 로그인한 사용자의 경우 메인페이지에서 팔로우한 사람의 게시글을 다 본 후에는 인기글이 보이도록 결정하였습니다.
인기글은 일주일 내에 작성한 게시글 중 좋아요가 많은 순서대로 보여줍니다.
테스트 코드도 작성했습니다.
> feat: 최근 일주일간의 인기글 조회

- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
- backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/repository/PostRepositoryTest.java
- backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- #326 
기존의 인기글 조회 로직은 메인 페이지의 게시물 조회 로직과 같은 방식으로 구현했지만, 인기글 조회는 좋아요 개수가 많은 순서대로 정렬되므로 postId를 기준 삼아서 게시글을 조회하는 방식은 오류를 발생했습니다.
따라서 최근 일주일간 생성된 게시물 중 좋아요 개수가 많은 순서대로 정렬된 게시물 리스트를 받은 다음, 프론트가 넘겨준 postId를 리스트에서 찾아서, 그 다음 게시물의 이미지를 반환하는 방식으로 변경하였습니다.
변경사항에 따라 테스트코드도 추가하고 수정했습니다.
> fix: 인기글 조회 로직 수정
