softeerbootcamp/Team2-CarBook

.idea/.gitignore, .idea/Team2.iml, .idea/gradle.xml, .idea/jarRepositories.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml
=> chore: 백엔드 프로젝트 세팅

frontend/carbook/.eslintrc.js, frontend/carbook/.gitignore, frontend/carbook/.prettierrc, frontend/carbook/index.html, frontend/carbook/package-lock.json, frontend/carbook/package.json, frontend/carbook/src/vite-env.d.ts, frontend/carbook/tsconfig.json
=> chore: 프론트 프로젝트 세팅

README.md
- close #14 
README.md ERD 사진 추가
x
x
=> docs: README.md ERD 사진 추가

README.md
- close #41 
README.md ERD 이미지 변경
=> docs: README.md ERD 이미지 변경

frontend/carbook/tsconfig.json, frontend/carbook/vite.config.ts
=> chore:절대경로 설정

frontend/carbook/index.html, frontend/carbook/package-lock.json, frontend/carbook/package.json, frontend/carbook/src/styles/color.scss, frontend/carbook/src/styles/global.scss, frontend/carbook/vite.config.ts
- close #81 
global, color, font, reset 설정하였습니다.
공통 color사용하실 때 color.scss 참고하여 쓰시면 됩니다.
X
X
=> chore: 스타일 관련 세팅

frontend/carbook/index.html, frontend/carbook/src/App.ts, frontend/carbook/src/core/Component.ts, frontend/carbook/src/core/index.ts, frontend/carbook/src/main.ts
- close #88 
프로젝트 디렉토리 세팅하였습니다.
X
=> chore: 프로젝트 디렉토리 세팅

frontend/carbook/src/App.ts, frontend/carbook/src/constants/eventName.ts, frontend/carbook/src/constants/path.ts, frontend/carbook/src/pages/HomePage.ts, frontend/carbook/src/pages/LoginPage.ts, frontend/carbook/src/pages/NotFoundPage.ts, frontend/carbook/src/pages/PostDetailPage.ts, frontend/carbook/src/pages/PostPage.ts, frontend/carbook/src/pages/ProfilePage.ts, frontend/carbook/src/pages/SignupPage.ts, frontend/carbook/src/pages/index.ts, frontend/carbook/src/utils/router/index.ts, frontend/carbook/src/utils/router/navigate.ts
- close #86 
history Api를 이용한 라우팅 기능 구현하였습니다.
- push(pathname) : pathname에 해당하는 페이지로 이동합니다.
- replace(pathname) : 현재 페이지를  pathname에 해당하는 페이지로 대체합니다.
X
X
=> feat: 라우팅 기능

backend/carbook/build.gradle, backend/carbook/sql/create_table.sql, backend/carbook/sql/drop_table.sql, backend/carbook/sql/sample_data.sql, backend/carbook/src/main/resources/application.properties
- close #84
- MySQL 연결 정보 추가
- DDL 추가
=> chore: DB 세팅

backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/SignupForm.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #10 
User 정보 입력 받기
dto 생성: 회원가입 정보를 입력받을 클래스 생성
UserController signup함수 추가 > 일단 String type return으로 처리
Postman으로 정보 입력 잘 되는지 확인 완료
=> feat: User 정보 입력 받기

frontend/carbook/src/api/axiosInstance.ts, frontend/carbook/src/api/index.ts
- close #83 
전역에서 사용할 axiosInstance를 만들었습니다.
- 쿠키 전송을 위해 withCredentials 설정을 true로 설정했습니다.
- baseUrl는 테스트를 위해 fakeserver의 url로 설정해 두었고 fakeserver와 테스트 할때는 withCredentials설정 제거 후 테스트 해야합니다
- instance 사용법: axiosInstance.get(url, ...)
- instance 사용예시: axiosInstance.post('/login',
{email : 'test@gmail.com', password  : 'carbook123'});
x
x
=> chore: axios 객체 생성

backend/carbook/build.gradle, backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/Message.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/SignupForm.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignUpEmailDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignUpNicknameDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupEmailDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupNicknameDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #17 
@Valid 어노테이션을 통해 이메일 형식이 아닐 경우, 닉네임이 16자 이상일 경우, 비밀번호가 16자 이상일 경우 제한
DAO 유저 추가, 이메일, 닉네임 중복체크 구현
응답을 위한 Message dto 추가 및 ResponseEntity로 응답 구현
=> feat: 입력받은 정보가 잘못된 형식일 경우 회원가입 제한

backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/LoginForm.java
- close #18 
UserController login 함수 작성
LoginForm dto class 생성
=> feat: user 로그인 입력 받기

backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/LoginForm.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/Message.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/LoginEmailNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #21 
- close #23 
UserService login 함수 설계, @Valid로 LoginForm 형식 제한
UserRepository 로그인 함수 로직 추가
UserSevice isLogin 함수 구현
ResponseEntity로 로그인 성공 여부 응답
=> feat: 잘못된 로그인 제한, 로그인 성공 처리

backend/carbook/.gitignore, backend/carbook/src/main/resources/application.properties
- close #84 
application properties git ignore에 추가
=> chore: application properties git ignore에 추가

backend/carbook/build.gradle, backend/carbook/sql/create_table.sql, backend/carbook/sql/sample_data.sql, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/Message.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- close #84 
build.gradle mysql connector import 방식 변경
sql문 수정 > 대문자로
UserRepository query 수정
406 error > Message dto getter 추가
=> chore: db 추가 세팅 - mysql 연결

frontend/carbook/src/pages/Signup/Signup.scss, frontend/carbook/src/pages/Signup/Signup.ts
- close #49 
회원가입 페이지 마크업 구현했습니다
x
=> feat: 회원가입 페이지 마크업

backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/SignupForm.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupNicknameDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java, backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- close #100 
- close #19 
ExceptionHandler 어노테이션으로 예외 처리
기존 서비스 단에서 ResponseEntity를 생성하던 것을 컨트롤러 단에서 생성
isLoginSuccess 함수 login으로 함수명 변경
Valid 어노테이션 methodargumentnotvalidexception으로 예외처리
SignupNicknameDuplicatedException 예외처리 커스텀 클래스 NicknameDuplicatedException로 이름 변경
테스트 코드 작성
=> feat: 예외처리, test 코드 작성

backend/carbook/sql/create_table.sql, backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/HashtagNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Hashtag.java, backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/GuestPostsResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/LoginPostsResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/model/Image.java, backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #34
재훈님과 같이 작업했습니다.
- Post 클래스 생성
- PostRepository 클래스 생성 및 getPosts() 메서드 구현
재훈님 작업 부분
- Image 클래스 생성
- 게시물 응답에 사용할 GuestPostsResponse 클래스 생성 및 구현
- ImageRepository 생성 및 구현
- PostService 클래스 생성 및 구현
- PostController 클래스 구현
- 로그인 시의 응답에 사용할 LoginPostsResponse 클래스 생성 및 구현
- Hashtag 클래스 생성
- HashtagRepository 클래스 생성 및 구현
- HashtagNotExistException 클래스 생성
- 키워드로 게시글 조회 시 사용할 응답 객체 PostSearchResponse 클래스 생성
- PostService에서 키워드로 게시물을 조회하는 searchByTags() 메서드 구현
- PostRepository에서 해시태그로 게시물을 조회하는 searchByHashtags() 메서드 구현
- PostController에 태그로 게시물을 조회하는 searchPostsByTags() 메서드 추가
- `PostRepository`에서 해시태그로 게시물을 조회하는 `searchByHashtags()` 메서드의 SQL 쿼리문이 많이 복잡한데, 괜찮은지 확인해주세요!
=> feat: 메인 페이지의 Post 도메인 작업과, 키워드를 통한 게시물 검색 기능 구현

backend/carbook/src/main/java/softeer/carbook/domain/follow/model/Follow.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- close #20 
#107 에 이어지는 작업입니다.
+ `Follow` 클래스 생성
+ `FollowRepository` 클래스 생성
+ `User` 및 `UserRepository`에 id 추가
+ HttpServlet을 메소드 인자로 받도록 수정
+ `PostRepository`에 유저가 팔로우하는 게시글을 조회하는 getFollowingPosts 메소드 추가
+ `PostService`에 유저가 팔로우하는 게시글을 위한 getRecentFollowerPosts 및 getImagesByPosts 메소드 추가
로그인 상태에서 포스트의 이미지를 가져오는 로직이 아직 기존의 post 1개 당 image 1개를 select하는 로직입니다. join 등을 활용하여 변경 요구됩니다.
=> feat: 메인 페이지의 로그인 상태 기능 및 팔로우 모델, 리포지토리 구현

frontend/carbook/src/components/Home/HashtagList.ts, frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/components/Home/index.ts, frontend/carbook/src/components/common/Header.ts, frontend/carbook/src/core/Component.ts, frontend/carbook/src/interfaces/index.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Home/Home.ts
- close #115 
메인 페이지 컴포넌트 분리작업
X
X
=> feat: 메인 페이지 컴포넌트 분리작업

backend/carbook/src/main/java/softeer/carbook/domain/post/dto/GuestPostsResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/LoginPostsResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/LoginEmailNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupEmailDuplicateException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #117 
+ response 에 builder 패턴 적용
+ user 레포지토리의 getEmailByNickname, getIdByNickname 등의 메소드를 제거 및 getUserByNickname으로 통일
X
X
=> refactor: 메인 페이지 response 및 user 레포지토리 리팩토링

frontend/carbook/src/pages/Login/Login.scss, frontend/carbook/src/pages/Login/Login.ts, frontend/carbook/src/pages/Signup/Signup.ts
- close #58 
로그인 페이지 input validation 체크했습니다.
빈값일 시 경고창 뜨고
성공시 메인 페이지로 이동합니다
https://user-images.githubusercontent.com/43432783/217710836-516c5e0f-6a01-4267-bffe-d257bf513ec1.mp4
회원가입과 로그인창에서의 경고 모달창이 거의 유사해서 컴포넌트로 뺄지 고민중입니다.
=> feat: login validation

frontend/carbook/src/components/Home/HashtagList.ts, frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/store/index.ts, frontend/carbook/src/store/tagStore.ts, frontend/carbook/src/utils/index.ts
- close #128 
태그를 추가하고 삭제할 수 있습니다.
(순서대로 들어오는 문제 해결 해야함 - 버그) 
X
X
=> feat: 태그 추가/삭제 기능

backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/ModifyFollowInfoForm.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyNickNameForm.java
- close #32 
팔로우 여부를 판단해서 팔로우 중일 경우 언팔로우, 언팔로우 중일 경우 팔로우 할 수 있게 구현했습니다.
포스트맨으로 테스트 완료했습니다.
=> feat: 팔로우/언팔로우 기능 구현

backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/FollowListResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- close #36
- close #37 
+ FollowController에서 팔로워, 팔로잉 목록 요청 조회
+ FollowService에서 팔로워, 팔로잉 닉네임 목록 조회
+ UserRepository에서 유저 닉네임을 통해 팔로워, 팔로잉 닉네임 조회
X
X
=> feat: 팔로잉, 팔로워 리스트 조회

backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
- close #135
- SELECT 쿼리문에서 "*"을 쓰지않고 컬럼명을 직접 사용하도록 변경
=> refactor: SELECT 쿼리문에서 "*"을 쓰지않고 컬럼명을 직접 사용하도록 변경

backend/carbook/build.gradle, backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
- close #137 
+ Bcrypt gradle에 추가
+ UserService에 비밀번호 암호화 메소드 추가
+ UserRepository의 addUser 메소드 인자 변경 (signupForm -> User)
+ id 없는 User 생성자 추가 (회원가입 시 id 제외한 signupForm이 들어오기 때문)
+ id 없는 User 생성자에서 id를 -1로 설정하고 있는데, 문제가 없을까요? 더 좋은 해결책이 있으시면 공유해주세요
=> feat: [로그인/회원가입] 비밀번호 암호화

frontend/carbook/src/api/axiosInstance.ts, frontend/carbook/src/core/Component.ts, frontend/carbook/vite.config.ts
- close #148 
서버와의 통신을 위해 proxy설정을 해주었습니다.
X
X
=> feat: proxy 설정

frontend/carbook/src/constants/errorMessage.ts, frontend/carbook/src/pages/Login/Login.scss, frontend/carbook/src/pages/Login/Login.ts, frontend/carbook/src/styles/color.scss
- close #57 
- id 이메일 형식 아니라면 이벤트 발생안함
- id, password가 잘못됐다면 경고창 보여준다
- 올바른 id, password 입력했다면 로그인 성공 알림을 보여주고 메인 페이지로 이동
https://user-images.githubusercontent.com/43432783/218307834-0b4d3ee3-9ad1-4aed-a77f-6a480ec0b21a.mp4
=> feat: 로그인 페이지 api 연결

frontend/carbook/src/api/index.ts, frontend/carbook/src/constants/errorMessage.ts, frontend/carbook/src/pages/Signup/Signup.scss, frontend/carbook/src/pages/Signup/Signup.ts
- close #56 
회원가입 페이지 서버와 api 연동했습니다
https://user-images.githubusercontent.com/43432783/218304882-da2c1aa9-0c52-41f1-99f7-506a94f705e1.mp4
=> feat: 회원가입 페이지 api 연동

backend/carbook/.gitignore, backend/carbook/build.gradle
- close #158 
이미지 업로드를 위한 S3 설정 
X
X
=> chore: s3 설정

frontend/carbook/src/components/Home/HashtagList.ts, frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/components/Home/SearchList.ts, frontend/carbook/src/components/Home/helper/index.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Home/Home.ts, frontend/carbook/src/utils/index.ts
- close #70 
키워드에 따른 이미지 리스트 보여주는 기능을 구현 하였습니다.
api가 변동 예정이라 나중에 한번 더 수정해야합니다  ㅠ
=> feat: 키워드에 따른 이미지 리스트 보여주기

backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java, backend/carbook/src/main/java/softeer/carbook/global/dto/Message.java, backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java, backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- close #170 
+ 팔로워 삭제 (친구삭제) 기능 구현
+ 기존 FollowRepository의 메소드를 활용하여 구현하였습니다.
X
X
=> feat: 팔로워 삭제 요청 구현

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/components/Post/TextForm.ts, frontend/carbook/src/components/Post/index.ts, frontend/carbook/src/components/common/Header.ts, frontend/carbook/src/pages/Home/Home.ts, frontend/carbook/src/pages/Post/Post.scss, frontend/carbook/src/pages/Post/Post.ts, frontend/carbook/src/utils/index.ts
- close #172 
글 작성 페이지 컴포넌트 분리
X
X
=> feat: 글 작성 페이지 컴포넌트 분리

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/pages/Post/Post.scss
- close #61
이미지를 등록할 수 있는 기능 구현하였습니다.
https://user-images.githubusercontent.com/67576476/218378507-71875135-8ba1-4d1d-b5c9-a40fe8cb880c.mov
X
=> feat: 이미지 등록 기능

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/Selection.ts
- close #66 
차모델/종류 select 기능을 구현하였습니다
아직 api가 완성되지 않아 콘솔엔 에러가 뜹니다.
X
X
=> feat: 차모델/종류 select 기능

backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/test/java/softeer/carbook/domain/hashtag/service/HashtagServiceTest.java, backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java, backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- close #168 
기존에 SpringBootTest로 실제 DB 값으로 테스트 했던 코드들을
Mockito를 활용해서 서비스단의 테스트 코드를 모두 수정 및 작성 하였습니다.
이제 db 값에 상관 없이 테스트가 잘 작동하도록 구현했습니다.
=> test: 기존 테스트 코드 수정

backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java, backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java, backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- close #177 
유저 서비스의 닉네임 변경, 비밀번호 변경과 프로필 페이지 컨트롤러 테스트 코드를 추가했습니다.
=> test: 프로필페이지 관련 테스트 코드 추가

backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
- close #189 
- #145
- `searchAllTags()`: 모든 태그 검색 기능 테스트
- `findAllTypes()`: 모든 차량 종류 조회 기능 테스트
- `findAllModels()`: 모든 차량 모델 조회 기능 테스트
=> test: TagService 테스트 코드 추가

backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- close #40
기존에 구현하지 않았던 해시태그 등록 기능을 추가하였습니다.
X
X
=> feat: 글 작성 페이지 해시태그 추가

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/SearchList.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/components/Post/TextForm.ts, frontend/carbook/src/pages/Post/Post.scss, frontend/carbook/src/utils/index.ts
- close #68 
각 컴포넌트에서 저장하고 있는 데이터 형태를
상위 컴포넌트에서 저장할 수 있도록 수정하였습니다.
+ 태그 삭제 기능이 빠져있어서 수정했습니다.
X
X
=> feat: 글 작성 페이지 form 기능

backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/ModifiedPostForm.java, backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/S3Repository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
- close #35 
+ 게시글 테이블 update 기능 구현
+ 이미지 테이블, post_hashtag 테이블, s3의 이미지는 수정페이지에서의 변경유무와 관계없이 삭제 후 재업로드
+ 글 생성과 수정에서 겹치는 일부 로직 메소드 분리
=> feat: 글 수정 구현

backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java, backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostDetailResponse.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/tag/service/TagService.java, backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java, backend/carbook/src/test/java/softeer/carbook/CarbookApplicationTests.java
- close #28 
글 상세 정보를 불러와 작성한 글을 볼 수 있는 api를 구현했습니다. 
먼저 로그인했는지 확인하고, 로그인한 경우 내가 쓴 글 페이지인지, 타인이 쓴 글 페이지인지 판단해서 응답으로 전달해주게 됩니다.
포스트맨으로 테스트 완료했습니다.
=> feat: 작성한 글 보기

frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/components/Home/SearchList.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/SearchList.ts, frontend/carbook/src/constants/wordLength.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Post/Post.scss, frontend/carbook/src/utils/index.ts
- close #69 
모달이 input.value.length >0 일 때만 보이도록 처리하고
loading 중일 때는 spinner가 보이도록 처리하였습니다.
X
X
=> feat: 모달 visible 처리

frontend/carbook/src/components/Home/Category.ts, frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/components/Home/SearchList.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/SearchList.ts, frontend/carbook/src/components/Post/TextForm.ts, frontend/carbook/src/interfaces/index.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/utils/index.ts
- close #205 
메인 페이지 전체 검색 안되는 버그 수정하였고
클릭 시 모달이 보이도록 수정하였습니다.
X
X
=> fix: 메인 페이지 전체 검색 안되는 버그 수정

frontend/carbook/src/api/index.ts, frontend/carbook/src/components/Home/SearchList.ts, frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/constants/errorMessage.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Post/Post.scss
- close #207 
차 모델/종류 선택 안되는 버그를 수정하였습니다.
종류에 따른 모델 선택은 글 수정 페이지에서 작성하겠습니다.
X
X
=> fix: 차 모델/종류 선택 안되는 버그 수정

backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java, backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- close #210 
글 상세 페이지 정보 불러오기, 글 삭제 관련 Controller, Service 단 테스트 코드를 작성했습니다.
=> test: 글 상세 페이지 관련 테스트코드 작성

frontend/carbook/src/components/Profile/FollowLists.ts, frontend/carbook/src/pages/Profile/Profile.ts
- close #183 
프로필 페이지에서 팔로우, 팔로잉 리스트에서 삭제 가능합니다
새로고침을 해야 팔로우, 팔로잉 수가 반영됩니다. (나중에 스토어를 쓰던지 해서 수정 예정)
=> feat: 팔로우 리스트에서 삭제

backend/carbook/src/main/java/softeer/carbook/domain/follow/exception/FollowIdNotExistException.java, backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java, backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java, backend/carbook/src/test/java/softeer/carbook/domain/follow/controller/FollowControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/follow/service/FollowServiceTest.java, backend/carbook/src/test/java/softeer/carbook/domain/like/controller/LikeControllerTest.java
- close #223 
팔로우 기능 관련 Controller, Service 단에서의 테스트 코드를 작성했습니다.
팔로워 취소 관련 로직에서 빠진 예외처리도 구현했습니다.
=> test: 팔로우 관련 테스트 코드 작성

frontend/carbook/src/components/Home/HashtagList.ts, frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/SearchForm.ts, frontend/carbook/src/components/Home/helper/index.ts, frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/components/Post/TextForm.ts, frontend/carbook/src/constants/post.ts, frontend/carbook/src/interfaces/index.ts, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Post/Post.ts, frontend/carbook/src/utils/index.ts
- close #80 
글 수정 기능 구현하였습니다.
X
X
=> feat: 글 수정 기능 

frontend/carbook/src/pages/Login/Login.scss, frontend/carbook/src/pages/Signup/Signup.scss
- close #230 
회원가입, 로그인 페이지 가운데 정렬 안된것 수정했습니다
https://user-images.githubusercontent.com/43432783/219281427-c2e61d63-d31c-4566-9534-6ff7788b3365.mp4
=> fix: 로그인, 회원가입 페이지 레이아웃 수정

backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
글 상세 페이지에서 진입한 사람의 닉네임이 뜨던 오류를 수정했습니다.
=> fix: 글 쓴 사람의 닉네임 전달하도록 수정

backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java, backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
이전 pr 로직 수정과 더불어 test 코드도 수정했습니다.
=> hotfix: test 코드 수정

frontend/carbook/src/components/PostDetail/InfoContents.ts, frontend/carbook/src/components/PostDetail/InfoHeader.ts, frontend/carbook/src/pages/PostDetail/PostDetail.scss, frontend/carbook/src/pages/PostDetail/PostDetail.ts
- close #76 
서버로부터 게시글 정보를 받아 게시글을 보여줍니다
뒤로가기 버튼을 누르면 이전 페이지로 이동하고
글 수정 버튼을 누르면 수정 페이지로 이동합니다.
글 삭제기능은 아직 구현하지 않았습니다.
=> feat: 상세 페이지 연결

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/constants/post.ts, frontend/carbook/src/interfaces/index.ts
- close #247 
글 수정이 안되는 버그를 수정하였습니다.
X
X
=> fix: 글 수정 기능

frontend/carbook/src/pages/PostDetail/PostDetail.ts, frontend/carbook/src/pages/Profile/Profile.ts
- close #79 
상세페이지에서 좋아요/ 좋아요 취소 가능
=> feat: 좋아요/좋아요 취소 기능 구현

frontend/carbook/src/pages/PostDetail/PostDetail.scss, frontend/carbook/src/pages/PostDetail/PostDetail.ts, frontend/carbook/src/pages/Profile/Profile.ts
- close #245 
글 상세 페이지 갱신해도 이전 정보 남아있는 버그 수정했습니다.
메뉴 버튼 애니메이션도 추가했습니다
=> fix:디테일 페이지 버그 수정

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/constants/post.ts, frontend/carbook/src/pages/Home/Home.ts, frontend/carbook/src/pages/PostDetail/PostDetail.ts
- close #229 
메인 페이지 state 초기화 안되는 버그 수정
X
X
=> fix: 메인 페이지 state 초기화 안되는 버그 수정

frontend/carbook/src/pages/Home/Home.ts, frontend/carbook/src/utils/isLogin.ts, frontend/carbook/src/utils/router/index.ts
- close #259 
isLogin 모듈 추가/ 페이지간 이벤트 쌓이는 문제 수정
X
X
=> feat: isLogin 모듈 추가/ 페이지간 이벤트 쌓이는 문제 수정

backend/carbook/src/test/resources/create_data.sql
- close #263 
리포지토리 테스트에 필요한 샘플데이터 삽입 sql입니다.
=> chore: create_data.sql 작성

frontend/carbook/src/components/PostDetail/InfoHeader.ts, frontend/carbook/src/pages/PostDetail/PostDetail.scss, frontend/carbook/src/pages/PostDetail/PostDetail.ts, frontend/carbook/src/pages/Profile/Profile.ts
- close #209 
- 글 상세 페이지에서 글 삭제를 누르면
- 성공 시 알림 창과 함께 메인페이지로 이동
- 실패 시 경고 알림창
=> feat: 글 상세 페이지 게시글 삭제 기능

backend/carbook/src/test/java/softeer/carbook/domain/follow/repository/FollowRepositoryTest.java
- close #261 
FollowRespository 테스트 코드 작성을 완료했습니다.
create_data.sql로 given을 처리하고 when, then만 작성했습니다.
=> test: FollowRepositoryTest 코드 작성

backend/carbook/src/test/java/softeer/carbook/domain/post/repository/PostRepositoryTest.java
- close #264
- PostRepository 테스트 코드 추가
=> test: PostRepository 테스트 코드 작성

frontend/carbook/src/components/Profile/Menu.ts, frontend/carbook/src/components/Profile/ModifyModal.ts, frontend/carbook/src/pages/Profile/Profile.scss, frontend/carbook/src/pages/Profile/Profile.ts
- close #194 
- 닉네임 변경창 사라질때 비밀번호 변경창 보이는 버그
- 프로필 페이지 유저 정보 수정 메뉴 아이템들 가려지는 버그 수정
- 비밀번호 변경 시 기존 비밀번호 틀렸을 때 오류 알림 메시지
- 비밀번호 변경 모달 닫았다가 열면 이전 정보들 남아있는것 수정
=> Fix: 프로필 페이지 버그 수정

frontend/carbook/src/pages/Login/Login.scss, frontend/carbook/src/pages/Login/Login.ts, frontend/carbook/src/pages/Signup/Signup.scss, frontend/carbook/src/pages/Signup/Signup.ts
- close #258 
- 로그인 페이지, 회원가입 페이지 크기가 작은것 수정
- 비밀번호 오류시 아이디가 틀렸다고 메시지 출력하던 것 수정
=> Fix: 로그인 페이지 버그

frontend/carbook/src/components/Profile/FollowLists.ts, frontend/carbook/src/pages/Profile/Profile.ts
- close #277 
- 팔로워, 팔로잉 삭제시 숫자도 감소하게 했습니다
=> feat: 팔로워, 팔로잉 삭제시 숫자 연동

frontend/carbook/src/components/Home/HashtagList.ts, frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/constants/post.ts, frontend/carbook/src/pages/Home/Home.ts
- close #212 
태그 삭제시 렌더링 안되는 버그 수정
X
X
=> fix: 태그 삭제시 렌더링 안되는 버그 수정

backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java, backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
- close #279 
+ 무한 스크롤에서 중복 및 누락 데이터 처리를 위해 기존의 index에서 postId를 활용하도록 쿼리 수정하였습니다.
=> feat: 무한 스크롤을 위한 쿼리 수정

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/SearchList.ts, frontend/carbook/src/components/Post/Selection.ts, frontend/carbook/src/pages/Post/Post.scss
- close #283 
글 작성페이지 input validation
X
X
=> feat: 글 작성페이지 input validation

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/pages/Home/Home.scss
- close #282 
메인 페이지 index -> postId로 변경
X
X
=> feat: 메인 페이지 index -> postId로 변경

backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java, backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java, backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
- close #292 
index -> postId로 변경하며 발생한 테스트코드 오류를 수정하였습니다.
=> test: postId를 활용한 테스트코드 작성

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Post/HashTagForm.ts, frontend/carbook/src/components/Post/SearchList.ts, frontend/carbook/src/pages/Post/Post.ts
- close #291 
- 메인 페이지 검색시 postid undefiend 처리
- 스켈레톤 안없어지는 버그 수정
- 해시태그 모달 다시 안뜨는 버그 수정
X
X
=> fix: 메인페이지 버그 수정

frontend/carbook/src/pages/PostDetail/PostDetail.scss, frontend/carbook/src/pages/PostDetail/PostDetail.ts
- close #280 
이미지 클릭시 원본 이미지 보여주고 x버튼 누르면 원래 게시글로 돌아옵니다
좋아요, 좋아요 취소시 애니메이션 추가했습니다
모델,종류 폰트 넷마블체로 변경했습니다
=> feat : 글 상세 페이지에서 이미지 클릭시 원본 보여주기

frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/helper/index.ts, frontend/carbook/src/constants/post.ts
- close #290 
form 이미지 초기화 안되는 버그 수정
X
X
=> fix: form 이미지 초기화 안되는 버그 수정

frontend/carbook/src/core/Component.ts, frontend/carbook/src/pages/PostDetail/PostDetail.ts, frontend/carbook/src/utils/index.ts
- close #287 
setstate함수에서 이전 state와 업데이트 될 state를 비교하고 같다면 리렌더링 하지 않습니다
=> chore: setState state 비교 로직 추가

backend/carbook/src/main/java/softeer/carbook/domain/tag/controller/TagController.java, backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java, backend/carbook/src/main/java/softeer/carbook/global/interceptor/LoginInterceptor.java, backend/carbook/src/main/java/softeer/carbook/global/interceptor/WebConfig.java, backend/carbook/src/test/java/softeer/carbook/domain/follow/controller/FollowControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/like/controller/LikeControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java, backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
- close #302 
spring의 interceptor 기능을 활용해 로그인 여부를 컨트롤러단 이전에 판단할 수 있도록 로직을 구현하였습니다.
테스트 코드와 포스트맨을 통해 테스트를 완료하였습니다.
=> feat: interceptor를 활용해 로그인 여부 처리

frontend/carbook/index.html, frontend/carbook/src/assets/icons/plus-white.svg, frontend/carbook/src/assets/icons/up.svg, frontend/carbook/src/assets/logo.svg, frontend/carbook/src/pages/Home/Home.scss, frontend/carbook/src/pages/Home/Home.ts, frontend/carbook/src/pages/PostDetail/PostDetail.ts
- close #300 
메인 페이지 위로가는 스크롤 추가
메타태그, 파비콘 적용
X
X
=> feat: 메인 페이지 위로가는 스크롤 추가

frontend/carbook/src/pages/PostDetail/PostDetail.scss, frontend/carbook/src/pages/PostDetail/PostDetail.ts
- close #309 
글 상세 페이지에서 배경이미지에 그래디언트 적용되지 않는것 수정
=> fix: 글 상세 페이지에서 뒤로가기 버튼 보이지 않는 것 수정

frontend/carbook/src/components/Home/Category.ts, frontend/carbook/src/components/Post/Form.ts, frontend/carbook/src/components/Post/ImageForm.ts, frontend/carbook/src/components/Post/helper/index.ts
- close #310 
태그 버그, 이미지 관련 버그 처리
X
X
=> fix: 태그 버그, 이미지 관련 버그 처리

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/helper/index.ts
- close #314 
이전 데이터 캐싱하여 페이지 이동시 데이터 유지
X
X
=> feat: 이전 데이터 캐싱하여 페이지 이동시 데이터 유지

frontend/carbook/src/components/PostDetail/InfoHeader.ts, frontend/carbook/src/components/Profile/helper/index.ts, frontend/carbook/src/constants/profileMode.ts, frontend/carbook/src/pages/Login/Login.scss, frontend/carbook/src/pages/Profile/Profile.ts, frontend/carbook/src/store/tagStore.ts
- close #313 
함수들 몇개들을 helper로 분리했습니다
=> Refactor: 함수 리팩토링

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/helper/index.ts, frontend/carbook/src/pages/Login/Login.ts
- close #317 
게시물 없을 때 좋아요 순 게시물 보여주는 기능
X
X
=> feat: 게시물 없을 때 좋아요 순 게시물 보여주는 기능

frontend/carbook/src/components/PostDetail/InfoContents.ts, frontend/carbook/src/pages/PostDetail/PostDetail.ts, frontend/carbook/src/store/tagStore.ts
- close #318 
글 상세 페이지에서 태그를 클릭하면 메인 페이지로 이동해서 태그와 관련 된 게시글 보여줍니다
=> feat: 글 상세 페이지에서 태그 누르면 메인페이지에서 필터링 된 게시글 보여줌

frontend/carbook/src/components/Home/PostList.ts, frontend/carbook/src/components/Home/helper/index.ts, frontend/carbook/src/components/Post/ImageForm.ts
- close #329 
좋아요 api 호출 버그 수정
api 호출 최소화하는 로직 추가
=> fix: 좋아요 api 호출 버그 수정

frontend/carbook/src/pages/PostDetail/PostDetail.ts
=> fix: image modal uri 수정
